<?php
$routes = [
    '' => ['controller' => 'HomeController', 'action' => 'index'],
    'home' => ['controller' => 'HomeController', 'action' => 'index'],
    'login' => ['controller' => 'AuthController', 'action' => 'login'],
    'register' => ['controller' => 'AuthController', 'action' => 'register'],
    'logout' => ['controller' => 'AuthController', 'action' => 'logout'],
    'catalog' => ['controller' => 'ProductController', 'action' => 'catalog'],
    'product' => ['controller' => 'ProductController', 'action' => 'show'],
    'rental' => ['controller' => 'RentalController', 'action' => 'create'],
    'rental/show' => ['controller' => 'RentalController', 'action' => 'show'],
    'rental/pay' => ['controller' => 'RentalController', 'action' => 'pay'],
    'rental/checkout' => ['controller' => 'RentalController', 'action' => 'checkout'],
    'rental/confirmation' => ['controller' => 'RentalController', 'action' => 'confirmation'],
    'rental/cancel' => ['controller' => 'RentalController', 'action' => 'cancel'],
    'rentals' => ['controller' => 'RentalController', 'action' => 'myRentals'],
    'dashboard' => ['controller' => 'DashboardController', 'action' => 'index'],
    'dashboard/add-product' => ['controller' => 'DashboardController', 'action' => 'addProduct'],
    'dashboard/edit-product' => ['controller' => 'DashboardController', 'action' => 'editProduct'],
    'dashboard/delete-product' => ['controller' => 'DashboardController', 'action' => 'deleteProduct'],
    'chat' => ['controller' => 'ChatController', 'action' => 'index'],
    'chat/send' => ['controller' => 'ChatController', 'action' => 'send'],
    'chat/messages' => ['controller' => 'ChatController', 'action' => 'getMessages'],
    'about' => ['controller' => 'PageController', 'action' => 'about'],
    'contact' => ['controller' => 'PageController', 'action' => 'contact'],
    'contact/send' => ['controller' => 'PageController', 'action' => 'sendContact'],
    'terms' => ['controller' => 'PageController', 'action' => 'terms'],
    'privacy' => ['controller' => 'PageController', 'action' => 'privacy'],
    'faq' => ['controller' => 'PageController', 'action' => 'faq'],

    'profile' => ['controller' => 'ProfileController', 'action' => 'index'],
    'profile/update' => ['controller' => 'ProfileController', 'action' => 'update'],
    'profile/delete' => ['controller' => 'ProfileController', 'action' => 'delete'],
];
?>
